import type { TechnologyRegistryEntry } from "./technology-types";

type HexColor = `#${string}`;

type TechnologySeed = readonly [
  label: string,
  slug: string,
  aliases: readonly string[],
  category: TechnologyRegistryEntry["category"],
  accent: HexColor,
];

type TechnologyThemeStyle = Pick<
  TechnologyRegistryEntry,
  "brandColor" | "color" | "light" | "dark"
>;

const LIGHT_BACKGROUND = "#F8FAFC" as const;
const LIGHT_TEXT = "#17232B" as const;
const DARK_BACKGROUND = "#17232B" as const;
const DARK_TEXT = "#F8FAFC" as const;
const LIGHT_BORDER_FALLBACK = "#64748B" as const;
const DARK_BORDER_FALLBACK = "#94A3B8" as const;
const MIN_BORDER_CONTRAST = 2.25;

const toLinearChannel = (channel: number) =>
  channel <= 0.03928
    ? channel / 12.92
    : ((channel + 0.055) / 1.055) ** 2.4;

const relativeLuminance = (hex: HexColor) => {
  const value = hex.slice(1);
  const red = toLinearChannel(Number.parseInt(value.slice(0, 2), 16) / 255);
  const green = toLinearChannel(Number.parseInt(value.slice(2, 4), 16) / 255);
  const blue = toLinearChannel(Number.parseInt(value.slice(4, 6), 16) / 255);

  return red * 0.2126 + green * 0.7152 + blue * 0.0722;
};

const contrastRatio = (foreground: HexColor, background: HexColor) => {
  const foregroundLuminance = relativeLuminance(foreground);
  const backgroundLuminance = relativeLuminance(background);
  const lighter = Math.max(foregroundLuminance, backgroundLuminance);
  const darker = Math.min(foregroundLuminance, backgroundLuminance);

  return (lighter + 0.05) / (darker + 0.05);
};

/**
 * Preserves each technology's canonical brand color while keeping badges
 * readable in both themes. Text uses high-contrast neutral colors; borders
 * fall back only when a brand color would disappear into the theme surface.
 */
const style = (accent: HexColor): TechnologyThemeStyle => ({
  brandColor: accent,
  color: accent,
  light: {
    bg: LIGHT_BACKGROUND,
    text: LIGHT_TEXT,
    border:
      contrastRatio(accent, LIGHT_BACKGROUND) >= MIN_BORDER_CONTRAST
        ? accent
        : LIGHT_BORDER_FALLBACK,
  },
  dark: {
    bg: DARK_BACKGROUND,
    text: DARK_TEXT,
    border:
      contrastRatio(accent, DARK_BACKGROUND) >= MIN_BORDER_CONTRAST
        ? accent
        : DARK_BORDER_FALLBACK,
  },
});

const entries = [
  // Technologies confirmed across the current portfolio and GitHub repositories.
  ["HTML", "html", ["html5"], "frontend", "#E34F26"],
  ["CSS", "css", ["css3"], "frontend", "#1572B6"],
  ["JavaScript", "javascript", ["js", "ecmascript"], "language", "#F7DF1E"],
  ["TypeScript", "typescript", ["ts"], "language", "#3178C6"],
  ["Java", "java", [], "language", "#ED8B00"],
  ["Python", "python", [], "language", "#3776AB"],
  ["PHP", "php", [], "language", "#777BB4"],
  ["C#", "c-sharp", ["csharp"], "language", "#68217A"],
  ["C++", "cpp", ["cplusplus", "c plus plus"], "language", "#00599C"],
  [".NET", "dotnet", ["dot net", "dotnet core"], "backend", "#512BD4"],
  ["YAML", "yaml", ["yml"], "language", "#CB171E"],
  ["Bash", "bash", ["shell", "shell script", "shell scripting", "bash scripting"], "language", "#4EAA25"],
  ["React", "react", ["reactjs", "react.js"], "frontend", "#61DAFB"],
  ["Next.js", "nextjs", ["next", "next.js"], "frontend", "#000000"],
  ["React Router", "react-router", ["react router dom", "react-router-dom"], "frontend", "#CA4245"],
  ["Axios", "axios", [], "frontend", "#5A29E4"],
  ["TanStack Query", "tanstack-query", ["react query", "tanstack"], "frontend", "#FF4154"],
  ["React Hook Form", "react-hook-form", ["rhf"], "frontend", "#EC5990"],
  ["Zustand", "zustand", [], "frontend", "#443E38"],
  ["Framer Motion", "framer-motion", ["framer"], "frontend", "#0055FF"],
  ["GSAP", "gsap", ["greensock"], "frontend", "#88CE02"],
  ["Tailwind CSS", "tailwind-css", ["tailwind", "tailwindcss"], "ui", "#06B6D4"],
  ["Sass", "sass", ["scss"], "ui", "#CC6699"],
  ["Bootstrap", "bootstrap", [], "ui", "#7952B3"],
  ["shadcn/ui", "shadcn-ui", ["shadcn"], "ui", "#18181B"],
  ["Radix UI", "radix-ui", ["radix"], "ui", "#161618"],
  ["Lucide React", "lucide-react", ["lucide"], "ui", "#F56565"],
  ["React Hot Toast", "react-hot-toast", ["hot toast"], "ui", "#FF4B4B"],
  ["Font Awesome", "font-awesome", ["fontawesome"], "ui", "#528DD7"],
  ["Google Fonts", "google-fonts", [], "ui", "#4285F4"],
  ["Node.js", "nodejs", ["node", "node.js"], "backend", "#339933"],
  ["Express.js", "expressjs", ["express", "express.js"], "backend", "#000000"],
  ["NestJS", "nestjs", ["nest"], "backend", "#E0234E"],
  ["GraphQL", "graphql", [], "backend", "#E10098"],
  ["Multer", "multer", [], "backend", "#8B5CF6"],
  ["MySQLi", "mysqli", ["mysql improved"], "backend", "#4479A1"],
  ["Apache HTTP Server", "apache-http-server", ["apache", "httpd"], "backend", "#D22128"],
  ["JSP", "jsp", ["java server pages", "jakarta server pages"], "backend", "#E76F00"],
  ["Java Servlet", "java-servlet", ["servlet", "servlets", "jakarta servlet"], "backend", "#5382A1"],
  ["Apache Tomcat", "apache-tomcat", ["tomcat"], "backend", "#F8DC75"],
  ["JSTL", "jstl", ["jsp standard tag library"], "backend", "#E76F00"],
  ["Spring Boot", "spring-boot", ["springboot"], "backend", "#6DB33F"],
  ["Spring Web", "spring-web", ["spring web mvc", "spring mvc"], "backend", "#6DB33F"],
  ["Nodemailer", "nodemailer", [], "messaging", "#009688"],
  ["Helmet", "helmet", ["helmet.js"], "backend", "#000000"],
  ["CORS", "cors", ["cross origin resource sharing"], "backend", "#2563EB"],
  ["Joi", "joi", ["joi validation"], "tooling", "#5E3BEE"],
  ["Spring Data JPA", "spring-data-jpa", ["spring jpa"], "database", "#6DB33F"],
  ["Hibernate", "hibernate", ["hibernate orm"], "database", "#59666C"],
  ["JDBC", "jdbc", ["java database connectivity"], "database", "#007396"],
  ["Spring Data MongoDB", "spring-data-mongodb", ["spring mongodb"], "database", "#6DB33F"],
  ["Maven", "maven", ["apache maven"], "tooling", "#C71A36"],
  ["Lombok", "lombok", ["project lombok"], "tooling", "#BC4521"],
  ["Java Faker", "java-faker", ["faker"], "tooling", "#3B82F6"],
  ["Spring Security", "spring-security", [], "auth", "#6DB33F"],
  ["Spring Boot Test", "spring-boot-test", ["spring testing"], "testing", "#6DB33F"],
  ["JUnit", "junit", ["junit 5", "junit5"], "testing", "#25A162"],
  ["MongoDB", "mongodb", ["mongo"], "database", "#47A248"],
  ["MongoDB Atlas", "mongodb-atlas", ["atlas"], "cloud", "#47A248"],
  ["Mongoose", "mongoose", [], "database", "#880000"],
  ["PostgreSQL", "postgresql", ["postgres", "psql"], "database", "#4169E1"],
  ["MySQL", "mysql", [], "database", "#4479A1"],
  ["MariaDB", "mariadb", [], "database", "#003545"],
  ["Redis", "redis", [], "database", "#DC382D"],
  ["Prisma", "prisma", [], "database", "#2D3748"],
  ["Drizzle ORM", "drizzle", ["drizzle orm"], "database", "#C5F74F"],
  ["Neon", "neon", ["neon database"], "cloud", "#00E699"],
  ["Amazon DynamoDB", "amazon-dynamodb", ["dynamodb"], "database", "#4053D6"],
  ["REST API", "rest-api", ["rest", "restful api"], "architecture", "#2563EB"],
  ["WebSocket", "websocket", ["web sockets", "websockets"], "messaging", "#2563EB"],
  ["Socket.IO", "socketio", ["socket io"], "messaging", "#010101"],
  ["Microservices", "microservices", ["microservice architecture"], "architecture", "#7C3AED"],
  ["Monorepo", "monorepo", ["mono repo"], "architecture", "#334155"],
  ["ES Modules", "es-modules", ["esm", "ecmascript modules"], "architecture", "#F7DF1E"],
  ["CommonJS", "commonjs", ["cjs"], "architecture", "#F7DF1E"],
  ["Kafka", "kafka", ["apache kafka"], "messaging", "#231F20"],
  ["JWT", "jwt", ["json web token", "jsonwebtoken"], "auth", "#000000"],
  ["OAuth", "oauth", ["oauth2", "oauth 2.0"], "auth", "#EB5424"],
  ["NextAuth.js", "nextauthjs", ["nextauth", "next auth", "auth.js", "authjs"], "auth", "#7C3AED"],
  ["bcrypt", "bcrypt", ["bcryptjs"], "auth", "#338033"],
  ["TensorFlow", "tensorflow", [], "ai-ml", "#FF6F00"],
  ["TensorFlow.js", "tensorflowjs", ["tensorflow js", "tfjs"], "ai-ml", "#FF6F00"],
  ["Groq", "groq", ["groq api"], "ai-ml", "#F55036"],
  ["Vercel AI SDK", "vercel-ai-sdk", ["ai sdk"], "ai-ml", "#000000"],
  ["RAG", "rag", ["retrieval augmented generation"], "ai-ml", "#7C3AED"],
  ["AWS", "aws", ["amazon web services"], "cloud", "#FF9900"],
  ["Amazon EC2", "amazon-ec2", ["ec2"], "cloud", "#FF9900"],
  ["Amazon VPC", "amazon-vpc", ["vpc"], "cloud", "#8C4FFF"],
  ["Amazon RDS", "amazon-rds", ["rds"], "cloud", "#527FFF"],
  ["AWS IAM", "aws-iam", ["iam"], "auth", "#DD344C"],
  ["AWS Auto Scaling", "aws-auto-scaling", ["auto scaling", "autoscaling"], "cloud", "#FF9900"],
  ["Elastic Load Balancing", "elastic-load-balancing", ["elb", "application load balancer", "alb"], "cloud", "#8C4FFF"],
  ["Amazon S3", "amazon-s3", ["s3"], "storage", "#569A31"],
  ["Vercel", "vercel", [], "cloud", "#000000"],
  ["Render", "render", ["render.com"], "cloud", "#46E3B7"],
  ["Cloudinary", "cloudinary", [], "storage", "#3448C5"],
  ["ImageKit", "imagekit", [], "storage", "#146EF5"],
  ["Docker", "docker", [], "devops", "#2496ED"],
  ["Docker Compose", "docker-compose", ["compose"], "devops", "#2496ED"],
  ["Docker Hub", "docker-hub", ["dockerhub"], "devops", "#2496ED"],
  ["Docker Buildx", "docker-buildx", ["buildx"], "devops", "#2496ED"],
  ["Kubernetes", "kubernetes", ["k8s"], "devops", "#326CE5"],
  ["Kubernetes HPA", "kubernetes-hpa", ["horizontal pod autoscaler", "hpa"], "devops", "#326CE5"],
  ["kubectl", "kubectl", [], "devops", "#326CE5"],
  ["Minikube", "minikube", [], "devops", "#2B2D42"],
  ["GitHub Actions", "github-actions", [], "devops", "#2088FF"],
  ["Linux", "linux", [], "devops", "#FCC624"],
  ["Jest", "jest", [], "testing", "#C21325"],
  ["Vitest", "vitest", [], "testing", "#6E9F18"],
  ["Playwright", "playwright", [], "testing", "#2EAD33"],
  ["Cypress", "cypress", [], "testing", "#17202C"],
  ["Supertest", "supertest", [], "testing", "#7B1FA2"],
  ["Postman", "postman", [], "testing", "#FF6C37"],
  ["Winston", "winston", ["winston logger"], "observability", "#231F20"],
  ["Morgan", "morgan", ["morgan logger"], "observability", "#000000"],
  ["ESLint", "eslint", [], "tooling", "#4B32C3"],
  ["Prettier", "prettier", [], "tooling", "#F7B93E"],
  ["Git", "git", [], "tooling", "#F05032"],
  ["GitHub", "github", [], "tooling", "#181717"],
  ["npm", "npm", ["node package manager"], "tooling", "#CB3837"],
  ["Vite", "vite", [], "tooling", "#646CFF"],
  ["Nx", "nx", ["nx monorepo"], "tooling", "#143055"],
  ["MDX", "mdx", [], "tooling", "#F9AC00"],
  ["MDXEditor", "mdxeditor", ["mdx editor"], "tooling", "#1F2937"],
  ["Swagger", "swagger", ["openapi", "swagger ui"], "tooling", "#85EA2D"],
  ["Zod", "zod", [], "tooling", "#3068B7"],
  ["XAMPP", "xampp", [], "tooling", "#FB7A24"],
  ["Eclipse IDE", "eclipse-ide", ["eclipse"], "tooling", "#2C2255"],
  ["Stripe", "stripe", [], "payment", "#635BFF"],
  ["Resend", "resend", [], "messaging", "#000000"],
  ["Concurrently", "concurrently", ["npm concurrently"], "tooling", "#5B45BB"],
  ["Nodemon", "nodemon", [], "tooling", "#76D04B"],
  ["dotenv", "dotenv", ["dot env"], "tooling", "#ECD53F"],
  ["PostCSS", "postcss", [], "tooling", "#DD3A0A"],
  ["Autoprefixer", "autoprefixer", [], "tooling", "#DD3735"],
  ["React Responsive", "react-responsive", ["react responsive"], "frontend", "#61DAFB"],
  ["Jackson", "jackson", ["fasterxml jackson"], "backend", "#2F6DB2"],
  ["Gson", "gson", ["google gson"], "backend", "#4285F4"],
  ["AWS SDK", "aws-sdk", ["amazon sdk", "aws sdk v2"], "cloud", "#FF9900"],
  ["Stripe CLI", "stripe-cli", [], "tooling", "#635BFF"],
  ["Pino", "pino", ["pino logger"], "observability", "#687634"],
  ["Sonner", "sonner", ["sonner toast"], "ui", "#111111"],
  ["Next Themes", "next-themes", ["next themes"], "frontend", "#000000"],
  ["Next MDX Remote", "next-mdx-remote", ["next mdx remote"], "tooling", "#F9AC00"],
  ["Day.js", "dayjs", ["day js"], "tooling", "#FF5F4C"],
  ["Slugify", "slugify", [], "tooling", "#F59E0B"],
  ["Class Variance Authority", "class-variance-authority", ["cva"], "ui", "#7C3AED"],
  ["clsx", "clsx", ["classnames utility"], "tooling", "#2563EB"],
  ["tailwind-merge", "tailwind-merge", ["tailwind merge"], "ui", "#06B6D4"],
  ["tailwindcss-animate", "tailwindcss-animate", ["tailwind animate"], "ui", "#06B6D4"],
  ["TanStack Table", "tanstack-table", ["react table", "tanstack table"], "frontend", "#FF4154"],
  ["ioredis", "ioredis", ["io redis"], "database", "#DC382D"],
  ["KafkaJS", "kafkajs", ["kafka js"], "messaging", "#231F20"],
  ["Cookie Parser", "cookie-parser", ["cookie parser"], "backend", "#8B5CF6"],
  ["Express Rate Limit", "express-rate-limit", ["express rate limiter"], "auth", "#2563EB"],
  ["Express HTTP Proxy", "express-http-proxy", ["express proxy"], "backend", "#000000"],
  ["EJS", "ejs", ["embedded javascript templates"], "frontend", "#A91E50"],
  ["node-cron", "node-cron", ["node cron"], "backend", "#339933"],
  ["React Quill", "react-quill", ["quill", "quill editor"], "ui", "#52B6E8"],
  ["sanitize-html", "sanitize-html", ["html sanitizer"], "auth", "#16A34A"],
  ["UAParser.js", "ua-parser-js", ["ua parser", "user agent parser"], "tooling", "#4B5563"],
  ["esbuild", "esbuild", [], "tooling", "#FFCF00"],
  ["SWC", "swc", ["speedy web compiler"], "tooling", "#F8C457"],
  ["Webpack", "webpack", [], "tooling", "#8DD6F9"],
  ["ts-jest", "ts-jest", ["typescript jest"], "testing", "#C21325"],
  ["Mailtrap", "mailtrap", [], "messaging", "#22D172"],
  ["Cross-env", "cross-env", ["cross env"], "tooling", "#4B5563"],
  ["dotenv-cli", "dotenv-cli", ["dotenv cli"], "tooling", "#ECD53F"],
  ["Drizzle Kit", "drizzle-kit", ["drizzlekit"], "tooling", "#C5F74F"],
  ["React DOM", "react-dom", ["reactdom"], "frontend", "#61DAFB"],
  ["Bright", "bright", ["bright syntax highlighter"], "ui", "#F59E0B"],
  ["query-string", "query-string", ["query string"], "tooling", "#1D4ED8"],
  ["nextjs-toploader", "nextjs-toploader", ["next top loader"], "ui", "#000000"],
  ["Pino Pretty", "pino-pretty", ["pino pretty"], "observability", "#687634"],

  // Future-ready catalog. Select these only after they are genuinely used in a project.
  ["Dart", "dart", [], "language", "#0175C2"],
  ["Go", "go", ["golang"], "language", "#00ADD8"],
  ["Rust", "rust", [], "language", "#000000"],
  ["Kotlin", "kotlin", [], "language", "#7F52FF"],
  ["Swift", "swift", [], "language", "#F05138"],
  ["SQL", "sql", ["structured query language"], "language", "#336791"],
  ["R", "r-language", ["r programming"], "language", "#276DC3"],
  ["React Native", "react-native", ["reactnative", "rn"], "mobile", "#61DAFB"],
  ["Expo", "expo", ["expo sdk"], "mobile", "#000020"],
  ["Expo Router", "expo-router", ["expo file based router"], "mobile", "#000020"],
  ["Expo Application Services", "expo-application-services", ["eas", "expo eas"], "mobile", "#000020"],
  ["Flutter", "flutter", [], "mobile", "#02569B"],
  ["NativeWind", "nativewind", ["native wind"], "mobile", "#06B6D4"],
  ["React Native Reanimated", "react-native-reanimated", ["reanimated"], "mobile", "#B5EC00"],
  ["Ionic", "ionic", [], "mobile", "#3880FF"],
  ["Capacitor", "capacitor", ["capacitor js"], "mobile", "#119EFF"],
  ["Android", "android", [], "mobile", "#3DDC84"],
  ["iOS", "ios", ["apple ios"], "mobile", "#000000"],
  ["Redux", "redux", [], "frontend", "#764ABC"],
  ["Redux Toolkit", "redux-toolkit", ["rtk"], "frontend", "#764ABC"],
  ["RTK Query", "rtk-query", ["redux toolkit query"], "frontend", "#764ABC"],
  ["Vue.js", "vuejs", ["vue", "vue.js"], "frontend", "#4FC08D"],
  ["Nuxt", "nuxt", ["nuxtjs", "nuxt.js"], "frontend", "#00DC82"],
  ["Angular", "angular", [], "frontend", "#DD0031"],
  ["Svelte", "svelte", [], "frontend", "#FF3E00"],
  ["SvelteKit", "sveltekit", ["svelte kit"], "frontend", "#FF3E00"],
  ["Astro", "astro", ["astrojs"], "frontend", "#BC52EE"],
  ["Remix", "remix", ["remix run"], "frontend", "#000000"],
  ["SolidJS", "solidjs", ["solid", "solid.js"], "frontend", "#2C4F7C"],
  ["Qwik", "qwik", ["qwik city"], "frontend", "#18B6F6"],
  ["HTMX", "htmx", [], "frontend", "#3366CC"],
  ["Alpine.js", "alpinejs", ["alpine", "alpine.js"], "frontend", "#8BC0D0"],
  ["Web Components", "web-components", ["custom elements"], "frontend", "#29ABE2"],
  ["Progressive Web App", "progressive-web-app", ["pwa"], "frontend", "#5A0FC8"],
  ["WebAssembly", "webassembly", ["wasm"], "frontend", "#654FF0"],
  ["Electron", "electron", ["electronjs"], "frontend", "#47848F"],
  ["Tauri", "tauri", [], "frontend", "#24C8D8"],
  ["Material UI", "material-ui", ["mui"], "ui", "#007FFF"],
  ["Chakra UI", "chakra-ui", ["chakra"], "ui", "#319795"],
  ["Ant Design", "ant-design", ["antd"], "ui", "#1677FF"],
  ["Storybook", "storybook", [], "ui", "#FF4785"],
  ["Motion", "motion", ["motion.dev"], "frontend", "#FFF312"],
  ["Bun", "bun", ["bun runtime"], "backend", "#FBF0DF"],
  ["Deno", "deno", [], "backend", "#000000"],
  ["Fastify", "fastify", [], "backend", "#000000"],
  ["Hono", "hono", ["hono js"], "backend", "#E36002"],
  ["Koa", "koa", ["koa.js"], "backend", "#33333D"],
  ["FastAPI", "fastapi", ["fast api"], "backend", "#009688"],
  ["Django", "django", [], "backend", "#092E20"],
  ["Flask", "flask", [], "backend", "#000000"],
  ["ASP.NET Core", "aspnet-core", ["asp.net core", "aspnet"], "backend", "#512BD4"],
  ["Laravel", "laravel", [], "backend", "#FF2D20"],
  ["Ruby on Rails", "ruby-on-rails", ["rails"], "backend", "#D30001"],
  ["tRPC", "trpc", ["t rpc"], "backend", "#398CCB"],
  ["gRPC", "grpc", [], "backend", "#244C5A"],
  ["Apollo GraphQL", "apollo-graphql", ["apollo client", "apollo server"], "backend", "#311C87"],
  ["GraphQL Yoga", "graphql-yoga", ["graphql yoga"], "backend", "#1B1B1F"],
  ["Server-Sent Events", "server-sent-events", ["sse"], "messaging", "#2563EB"],
  ["WebRTC", "webrtc", ["web rtc"], "messaging", "#333333"],
  ["BullMQ", "bullmq", ["bull mq"], "messaging", "#DC382D"],
  ["RabbitMQ", "rabbitmq", ["rabbit mq"], "messaging", "#FF6600"],
  ["NATS", "nats", ["nats io"], "messaging", "#27AAE1"],
  ["Temporal", "temporal", ["temporal io"], "architecture", "#000000"],
  ["Celery", "celery", [], "messaging", "#37814A"],
  ["Webhooks", "webhooks", ["webhook"], "architecture", "#7C3AED"],
  ["Supabase", "supabase", [], "cloud", "#3ECF8E"],
  ["Firebase", "firebase", [], "cloud", "#FFCA28"],
  ["Cloud Firestore", "cloud-firestore", ["firestore"], "database", "#FFCA28"],
  ["SQLite", "sqlite", [], "database", "#003B57"],
  ["Turso", "turso", ["libsql"], "database", "#4FF8D2"],
  ["PlanetScale", "planetscale", ["planet scale"], "database", "#000000"],
  ["CockroachDB", "cockroachdb", ["cockroach db"], "database", "#6933FF"],
  ["TimescaleDB", "timescaledb", ["timescale"], "database", "#FDB515"],
  ["pgvector", "pgvector", ["postgres vector"], "database", "#4169E1"],
  ["Pinecone", "pinecone", ["pinecone db"], "database", "#000000"],
  ["Qdrant", "qdrant", [], "database", "#DC244C"],
  ["Weaviate", "weaviate", [], "database", "#00B977"],
  ["Chroma", "chroma", ["chromadb", "chroma db"], "database", "#FFDE2D"],
  ["Elasticsearch", "elasticsearch", ["elastic search"], "database", "#005571"],
  ["OpenSearch", "opensearch", ["open search"], "database", "#005EB8"],
  ["Apache Cassandra", "apache-cassandra", ["cassandra"], "database", "#1287B1"],
  ["ClickHouse", "clickhouse", ["click house"], "database", "#FFCC01"],
  ["Upstash", "upstash", [], "cloud", "#00E9A3"],
  ["Convex", "convex", ["convex dev"], "cloud", "#F3B01C"],
  ["MinIO", "minio", ["minio storage"], "storage", "#C72E49"],
  ["OpenID Connect", "openid-connect", ["oidc"], "auth", "#F78C40"],
  ["Auth0", "auth0", [], "auth", "#EB5424"],
  ["Clerk", "clerk", ["clerk auth"], "auth", "#6C47FF"],
  ["Keycloak", "keycloak", [], "auth", "#4D4D4D"],
  ["Passport.js", "passportjs", ["passport", "passport.js"], "auth", "#34E27A"],
  ["Better Auth", "better-auth", ["betterauth"], "auth", "#000000"],
  ["Firebase Authentication", "firebase-authentication", ["firebase auth"], "auth", "#FFCA28"],
  ["Role-Based Access Control", "role-based-access-control", ["rbac"], "auth", "#7C3AED"],
  ["Cloudflare Workers", "cloudflare-workers", ["workers"], "cloud", "#F38020"],
  ["Cloudflare R2", "cloudflare-r2", ["r2 storage"], "storage", "#F38020"],
  ["AWS Lambda", "aws-lambda", ["lambda"], "cloud", "#FF9900"],
  ["Amazon API Gateway", "amazon-api-gateway", ["api gateway"], "cloud", "#FF4F8B"],
  ["Amazon ECS", "amazon-ecs", ["ecs"], "cloud", "#FF9900"],
  ["Amazon EKS", "amazon-eks", ["eks"], "cloud", "#FF9900"],
  ["AWS Fargate", "aws-fargate", ["fargate"], "cloud", "#FF9900"],
  ["Amazon CloudFront", "amazon-cloudfront", ["cloudfront"], "cloud", "#8C4FFF"],
  ["Amazon Route 53", "amazon-route-53", ["route 53", "route53"], "cloud", "#8C4FFF"],
  ["AWS Secrets Manager", "aws-secrets-manager", ["secrets manager"], "cloud", "#DD344C"],
  ["Amazon SQS", "amazon-sqs", ["sqs"], "messaging", "#FF4F8B"],
  ["Amazon SNS", "amazon-sns", ["sns"], "messaging", "#FF4F8B"],
  ["Amazon EventBridge", "amazon-eventbridge", ["eventbridge"], "messaging", "#FF4F8B"],
  ["AWS SES", "aws-ses", ["amazon ses", "simple email service"], "messaging", "#FF9900"],
  ["Google Cloud", "google-cloud", ["gcp", "google cloud platform"], "cloud", "#4285F4"],
  ["Microsoft Azure", "microsoft-azure", ["azure"], "cloud", "#0078D4"],
  ["Netlify", "netlify", [], "cloud", "#00C7B7"],
  ["Railway", "railway", ["railway app"], "cloud", "#0B0D0E"],
  ["Fly.io", "flyio", ["fly io"], "cloud", "#7B3FF2"],
  ["DigitalOcean", "digitalocean", ["digital ocean"], "cloud", "#0080FF"],
  ["Heroku", "heroku", [], "cloud", "#430098"],
  ["Terraform", "terraform", ["infrastructure as code", "iac"], "devops", "#844FBA"],
  ["OpenTofu", "opentofu", ["open tofu"], "devops", "#FFDA18"],
  ["Pulumi", "pulumi", [], "devops", "#8A3391"],
  ["AWS CDK", "aws-cdk", ["cloud development kit"], "devops", "#FF9900"],
  ["Ansible", "ansible", [], "devops", "#EE0000"],
  ["Helm", "helm", ["helm charts"], "devops", "#0F1689"],
  ["Argo CD", "argo-cd", ["argocd"], "devops", "#EF7B4D"],
  ["GitLab CI/CD", "gitlab-ci-cd", ["gitlab ci", "gitlab cicd"], "devops", "#FC6D26"],
  ["Jenkins", "jenkins", [], "devops", "#D24939"],
  ["CircleCI", "circleci", ["circle ci"], "devops", "#343434"],
  ["Nginx", "nginx", [], "devops", "#009639"],
  ["Traefik", "traefik", [], "devops", "#24A1C1"],
  ["Caddy", "caddy", ["caddy server"], "devops", "#1F88C0"],
  ["Serverless Framework", "serverless-framework", ["serverless"], "devops", "#FD5750"],
  ["pnpm", "pnpm", [], "tooling", "#F69220"],
  ["Yarn", "yarn", [], "tooling", "#2C8EBB"],
  ["OpenTelemetry", "opentelemetry", ["otel"], "observability", "#F5A800"],
  ["Prometheus", "prometheus", [], "observability", "#E6522C"],
  ["Grafana", "grafana", [], "observability", "#F46800"],
  ["Sentry", "sentry", [], "observability", "#362D59"],
  ["Datadog", "datadog", [], "observability", "#632CA6"],
  ["Jaeger", "jaeger", ["jaeger tracing"], "observability", "#66CFE3"],
  ["Grafana Loki", "grafana-loki", ["loki"], "observability", "#F2CC0C"],
  ["Kibana", "kibana", [], "observability", "#005571"],
  ["New Relic", "new-relic", ["newrelic"], "observability", "#1CE783"],
  ["LangSmith", "langsmith", ["lang smith"], "observability", "#1C3C3C"],
  ["Weights & Biases", "weights-and-biases", ["wandb", "weights and biases"], "observability", "#FFBE00"],
  ["Testing Library", "testing-library", ["react testing library", "rtl"], "testing", "#E33332"],
  ["Mock Service Worker", "mock-service-worker", ["msw"], "testing", "#FF6A33"],
  ["k6", "k6", ["grafana k6"], "testing", "#7D64FF"],
  ["Testcontainers", "testcontainers", ["test containers"], "testing", "#2496ED"],
  ["Selenium", "selenium", [], "testing", "#43B02A"],
  ["Pact", "pact", ["pact testing"], "testing", "#F3B13E"],
  ["Artillery", "artillery", ["artillery io"], "testing", "#F97316"],
  ["OpenAI API", "openai-api", ["openai"], "ai-ml", "#10A37F"],
  ["OpenAI Agents SDK", "openai-agents-sdk", ["openai agents", "agents sdk"], "ai-ml", "#10A37F"],
  ["Anthropic Claude", "anthropic-claude", ["claude", "anthropic"], "ai-ml", "#D97757"],
  ["Google Gemini", "google-gemini", ["gemini", "gemini api"], "ai-ml", "#8E75B2"],
  ["Hugging Face", "hugging-face", ["huggingface"], "ai-ml", "#FFD21E"],
  ["PyTorch", "pytorch", [], "ai-ml", "#EE4C2C"],
  ["scikit-learn", "scikit-learn", ["sklearn"], "ai-ml", "#F7931E"],
  ["LangChain", "langchain", ["lang chain"], "ai-ml", "#1C3C3C"],
  ["LangGraph", "langgraph", ["lang graph"], "ai-ml", "#1C3C3C"],
  ["LlamaIndex", "llamaindex", ["llama index"], "ai-ml", "#8B5CF6"],
  ["Ollama", "ollama", [], "ai-ml", "#000000"],
  ["Model Context Protocol", "model-context-protocol", ["mcp"], "ai-ml", "#7C3AED"],
  ["AI Agents", "ai-agents", ["agentic ai", "agent systems"], "ai-ml", "#7C3AED"],
  ["Vector Database", "vector-database", ["vector db"], "architecture", "#7C3AED"],
  ["ONNX Runtime", "onnx-runtime", ["onnx"], "ai-ml", "#005CED"],
  ["OpenCV", "opencv", [], "ai-ml", "#5C3EE8"],
  ["spaCy", "spacy", [], "ai-ml", "#09A3D5"],
  ["Event-Driven Architecture", "event-driven-architecture", ["eda"], "architecture", "#7C3AED"],
  ["Clean Architecture", "clean-architecture", [], "architecture", "#2563EB"],
  ["Hexagonal Architecture", "hexagonal-architecture", ["ports and adapters"], "architecture", "#2563EB"],
  ["Domain-Driven Design", "domain-driven-design", ["ddd"], "architecture", "#7C3AED"],
  ["CQRS", "cqrs", ["command query responsibility segregation"], "architecture", "#7C3AED"],
  ["Event Sourcing", "event-sourcing", [], "architecture", "#7C3AED"],
  ["Serverless Architecture", "serverless-architecture", ["serverless computing"], "architecture", "#FF9900"],
  ["Edge Computing", "edge-computing", ["edge runtime"], "architecture", "#F38020"],
  ["Backend for Frontend", "backend-for-frontend", ["bff"], "architecture", "#2563EB"],
  ["PayPal", "paypal", [], "payment", "#003087"],
  ["PayHere", "payhere", ["payhere sri lanka"], "payment", "#E31B23"],
  ["Twilio", "twilio", [], "messaging", "#F22F46"],
  ["SendGrid", "sendgrid", ["twilio sendgrid"], "messaging", "#1A82E2"],
] as const satisfies readonly TechnologySeed[];

export const TECHNOLOGY_REGISTRY = entries.map(
  ([label, slug, aliases, category, accent]) => ({
    label,
    slug,
    aliases,
    category,
    ...style(accent),
  }),
) satisfies readonly TechnologyRegistryEntry[];

export const TECHNOLOGY_REGISTRY_BY_SLUG = Object.fromEntries(
  TECHNOLOGY_REGISTRY.map((entry) => [entry.slug, entry]),
) as Record<string, TechnologyRegistryEntry>;
