"use client";

import { TECH_TAG_CATEGORY_DEFINITIONS, createCustomTechnologySlug, findTechnologyByNameOrAlias, findTechnologyBySlug, getTechTagCategoryLabel, searchTechnologies, type ProjectTechStackItem, type TechTagCategory, type TechnologySlug } from "@portfolio/shared";
import { Plus, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";

type Props = { value: ProjectTechStackItem[]; onChange: (value: ProjectTechStackItem[]) => void; onValidityChange?: (valid: boolean) => void };
const accent = "#64748B" as const;

export function TechStackInput({ value, onChange, onValidityChange }: Props) {
  const [query, setQuery] = useState("");
  const results = useMemo(() => searchTechnologies(query).slice(0, 8), [query]);
  const selected = new Set(value.filter((item): item is Extract<ProjectTechStackItem, { kind: "known" }> => item.kind === "known").map((item) => item.slug));
  const addKnown = (slug: TechnologySlug) => { if (selected.has(slug)) return; onChange([...value, { kind: "known", slug, showOnCard: false }]); setQuery(""); };
  const addCustom = () => { const label = query.trim(); if (!label || findTechnologyByNameOrAlias(label)) return; onChange([...value, { kind: "custom", slug: createCustomTechnologySlug(label), label, category: "other", color: accent, showOnCard: false }]); setQuery(""); };
  const update = (index: number, item: ProjectTechStackItem) => onChange(value.map((current, currentIndex) => currentIndex === index ? item : current));
  const valid = value.length > 0 && value.every((item) => item.kind === "known" || (item.label.trim() && item.slug && /^#[0-9a-fA-F]{6}$/.test(item.color)));
  useEffect(() => { onValidityChange?.(valid); }, [onValidityChange, valid]);
  return <section className="space-y-3" aria-labelledby="technology-stack-heading">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 id="technology-stack-heading" className="text-sm font-medium text-[var(--admin-text)]">Technology stack</h3><p className="mt-1 text-xs text-[var(--admin-muted)]">Search the canonical registry or create a custom technology.</p></div><Button type="button" size="sm" onClick={addCustom} disabled={!query.trim() || Boolean(findTechnologyByNameOrAlias(query))}><Plus className="size-4" aria-hidden="true" />Create custom</Button></div>
    <label className="sr-only" htmlFor="technology-search">Search technology by name, alias, or slug</label><Input id="technology-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search React, next.js, k8s…" role="combobox" aria-controls="technology-options" aria-expanded={Boolean(query)} />
    {query ? <div id="technology-options" role="listbox" className="grid gap-1 rounded-lg border border-[var(--admin-border)] bg-[var(--admin-surface)] p-2">{results.length ? results.map((entry) => <button type="button" role="option" aria-selected={selected.has(entry.slug)} disabled={selected.has(entry.slug)} key={entry.slug} onClick={() => addKnown(entry.slug)} className="flex items-center justify-between rounded-md px-3 py-2 text-left text-sm hover:bg-[var(--admin-accent-soft)] disabled:opacity-50"><span><span className="font-medium">{entry.label}</span><span className="ml-2 text-xs text-[var(--admin-muted)]">{getTechTagCategoryLabel(entry.category)}</span></span><span className="size-3 rounded-full" style={{ backgroundColor: entry.color }} aria-label={`Accent ${entry.color}`} /></button>) : <p className="px-3 py-2 text-sm text-[var(--admin-muted)]">No known technology found. Use Create custom.</p>}</div> : null}
    <div className="space-y-2">{value.map((item, index) => { const entry = item.kind === "known" ? findTechnologyBySlug(item.slug) : undefined; const label = item.kind === "known" ? (entry?.label ?? item.slug) : item.label; return <div key={`${item.kind}-${item.slug}-${index}`} className="grid gap-2 rounded-lg border border-[var(--admin-border)] bg-[var(--admin-surface-muted)] p-3 sm:grid-cols-[1fr_10rem_auto_auto]"><div><p className="text-sm font-medium text-[var(--admin-text)]">{label}</p><p className="text-xs text-[var(--admin-muted)]">{item.kind === "known" ? `${getTechTagCategoryLabel(entry?.category ?? "other")} · registry metadata` : "Custom technology"}</p>{item.kind === "custom" ? <div className="mt-2 grid gap-2 sm:grid-cols-2"><Input aria-label={`Custom label ${index + 1}`} value={item.label} onChange={(e) => update(index, { ...item, label: e.target.value, slug: createCustomTechnologySlug(e.target.value) })} placeholder="Label" /><Select value={item.category} onValueChange={(category) => update(index, { ...item, category: category as TechTagCategory })}><SelectTrigger aria-label={`Custom category ${index + 1}`}><SelectValue /></SelectTrigger><SelectContent>{TECH_TAG_CATEGORY_DEFINITIONS.map((category) => <SelectItem key={category.value} value={category.value}>{category.label}</SelectItem>)}</SelectContent></Select></div> : null}</div><span className="flex items-center text-xs text-[var(--admin-muted)]">{item.kind === "known" ? "Automatic light/dark styles" : <><input type="color" aria-label={`Custom accent color ${index + 1}`} value={item.color} onChange={(e) => update(index, { ...item, color: e.target.value as `#${string}` })} /></>}</span><label className="flex items-center gap-2 text-xs"><Switch checked={item.showOnCard} onCheckedChange={(checked) => update(index, { ...item, showOnCard: checked })} aria-label={`Show ${label} on project card`} />Card</label><Button type="button" variant="secondary" size="sm" onClick={() => onChange(value.filter((_, itemIndex) => itemIndex !== index))} aria-label={`Remove ${label}`}><Trash2 className="size-4" aria-hidden="true" /></Button></div>; })}</div>
    {!valid ? <p className="text-xs text-red-700" role="alert">Add at least one complete technology and remove empty custom fields.</p> : null}
  </section>;
}
